### ISSUE TITLE
show our rule/example in docs and cli base on yaml file

### ISSUE THREAD

**Issue by zhongjiajie** [WhaleOps/airphin#21]
currently, we have rule with

```yaml
name: DummyOperator
description: The configuration for converting Airflow DummyOperator to DolphinScheduler Shell task.

migration:
  module:
    src: airflow.operators.dummy_operator.DummyOperator
    dest: pydolphinschsduler.tasks.shell.Shell
  parameter:
    - src: task_id
      dest: name
    - src: bash_command
      dest: command
      default: echo 'Airflow DummyOperator'
```

maybe we should add new tag `example`, for the migrate which include `src` and `dest`,

```yaml
name: DummyOperator
description: The configuration for converting Airflow DummyOperator to DolphinScheduler Shell task.

migration:
  ...

example:
  - src: syntax_before
  - dest: syntax_after
```
